version: "3.8"
services:
  sqlserverdev:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_SA_PASSWORD: "DDDinPractice2021"
      ACCEPT_EULA: "Y"
    hostname: ddd-in-practice
    container_name: ddd-in-practice
    ports:
      - 1433:1433
    volumes:
      - sqldevvolume:/var/opt/mssql
volumes:
  sqldevvolume: 